apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl

spec:
  replicas: 1 # number pods
  selector: # which pod to manage
    matchLabels:
      app: posts

  template: # how a pod look like
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: sanjayadhi/posts:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clsip-srv
spec:
  selector:
    app: posts # same label
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000

