apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: sanjayadhi/blog-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"

    - image: sanjayadhi/comments
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"

    - image: sanjayadhi/event-bus
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"

    - image: sanjayadhi/posts
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"

    - image: sanjayadhi/moderation
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"

    - image: sanjayadhi/query
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*.js"
